# Generated by Django 5.0.6 on 2024-10-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_companyinfo_certificate_alter_companyinfo_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(default='asdf', max_length=255),
            preserve_default=False,
        ),
    ]
